AWSTemplateFormatVersion: '2010-09-09'
Description: "CloudFormation template to create an AWS CodePipeline with GitHub integration and CodeBuild"

Parameters:
  GitHubRepoOwner:
    Description: "The GitHub repository owner (username or organization)"
    Type: String
    Default: "my-github-user"

  GitHubRepoName:
    Description: "The name of the GitHub repository"
    Type: String
    Default: "my-github-repo"

  GitHubBranch:
    Description: "The branch to monitor in the GitHub repository"
    Type: String
    Default: "main"

  GitHubOAuthToken:
    Description: "OAuth token to connect to the GitHub repository"
    Type: String
    NoEcho: true

  S3Bucket:
    Description: "S3 bucket for storing pipeline artifacts"
    Type: String
    Default: "my-artifact-bucket"

Resources:
  # S3 Bucket for storing pipeline artifacts
  PipelineS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref S3Bucket
      VersioningConfiguration:
        Status: Enabled

  # IAM Role for CodePipeline
  CodePipelineServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codepipeline.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: "CodePipelinePolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                  - s3:GetBucketVersioning
                  - codebuild:*
                Resource: "*"

  # IAM Role for CodeBuild
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Path: "/"
      Policies:
        - PolicyName: "CodeBuildPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:ListBucket
                Resource: "*"
        - PolicyName: "CodeBuildCloudWatchLogsPolicy"
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: "*"

  # CodePipeline definition with GitHub as the source
  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      RoleArn: !GetAtt CodePipelineServiceRole.Arn
      ArtifactStore:
        Type: S3
        Location: !Ref PipelineS3Bucket
      Stages:
        - Name: Source
          Actions:
            - Name: GitHubSource
              ActionTypeId:
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
                Version: "1"
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                Owner: !Ref GitHubRepoOwner
                Repo: !Ref GitHubRepoName
                Branch: !Ref GitHubBranch
                OAuthToken: !Ref GitHubOAuthToken
              RunOrder: 1

        - Name: Build
          Actions:
            - Name: CodeBuildAction
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: "1"
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
              RunOrder: 1

  # CodeBuild Project Definition
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: "MyBuildProject"
      Source:
        Type: CODEPIPELINE
      Artifacts:
        Type: CODEPIPELINE
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: "aws/codebuild/standard:5.0"   # CodeBuild standard environment
        Type: LINUX_CONTAINER
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn

Outputs:
  PipelineUrl:
    Description: "URL of the CodePipeline"
    Value: !Sub "https://console.aws.amazon.com/codesuite/codepipeline/pipelines/${CodePipeline}/view"
